data=read.csv("D:\\R-3.6.1\\obese.csv")
summary(data)
model=lm(data$obese~ data$ ï..sex +data$sbp + data$dbp + data$scl +data$age +data$bmi)
plot(model)
plot(data)
summary(model)
resid(model)
fitted(model)
par(mfrow=c(2,2))
model=lm(data$obese ~ data$sbp +data$dbp)
summary(model)
plot(model)
